# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/trw/Documents/Repos/test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/trw/Documents/Repos/test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trw/Documents/Repos/test/CMakeFiles /home/trw/Documents/Repos/test//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trw/Documents/Repos/test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testApp

# Build rule for target.
testApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testApp
.PHONY : testApp

# fast build rule for target.
testApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/build
.PHONY : testApp/fast

Buffers.o: Buffers.cpp.o
.PHONY : Buffers.o

# target to build an object file
Buffers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Buffers.cpp.o
.PHONY : Buffers.cpp.o

Buffers.i: Buffers.cpp.i
.PHONY : Buffers.i

# target to preprocess a source file
Buffers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Buffers.cpp.i
.PHONY : Buffers.cpp.i

Buffers.s: Buffers.cpp.s
.PHONY : Buffers.s

# target to generate assembly for a file
Buffers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Buffers.cpp.s
.PHONY : Buffers.cpp.s

Camera.o: Camera.cpp.o
.PHONY : Camera.o

# target to build an object file
Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Camera.cpp.o
.PHONY : Camera.cpp.o

Camera.i: Camera.cpp.i
.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s
.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

CbtBisection.o: CbtBisection.cpp.o
.PHONY : CbtBisection.o

# target to build an object file
CbtBisection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/CbtBisection.cpp.o
.PHONY : CbtBisection.cpp.o

CbtBisection.i: CbtBisection.cpp.i
.PHONY : CbtBisection.i

# target to preprocess a source file
CbtBisection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/CbtBisection.cpp.i
.PHONY : CbtBisection.cpp.i

CbtBisection.s: CbtBisection.cpp.s
.PHONY : CbtBisection.s

# target to generate assembly for a file
CbtBisection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/CbtBisection.cpp.s
.PHONY : CbtBisection.cpp.s

CbtGpuBisection.o: CbtGpuBisection.cpp.o
.PHONY : CbtGpuBisection.o

# target to build an object file
CbtGpuBisection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/CbtGpuBisection.cpp.o
.PHONY : CbtGpuBisection.cpp.o

CbtGpuBisection.i: CbtGpuBisection.cpp.i
.PHONY : CbtGpuBisection.i

# target to preprocess a source file
CbtGpuBisection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/CbtGpuBisection.cpp.i
.PHONY : CbtGpuBisection.cpp.i

CbtGpuBisection.s: CbtGpuBisection.cpp.s
.PHONY : CbtGpuBisection.s

# target to generate assembly for a file
CbtGpuBisection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/CbtGpuBisection.cpp.s
.PHONY : CbtGpuBisection.cpp.s

Context.o: Context.cpp.o
.PHONY : Context.o

# target to build an object file
Context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Context.cpp.o
.PHONY : Context.cpp.o

Context.i: Context.cpp.i
.PHONY : Context.i

# target to preprocess a source file
Context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Context.cpp.i
.PHONY : Context.cpp.i

Context.s: Context.cpp.s
.PHONY : Context.s

# target to generate assembly for a file
Context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Context.cpp.s
.PHONY : Context.cpp.s

Device.o: Device.cpp.o
.PHONY : Device.o

# target to build an object file
Device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Device.cpp.o
.PHONY : Device.cpp.o

Device.i: Device.cpp.i
.PHONY : Device.i

# target to preprocess a source file
Device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Device.cpp.i
.PHONY : Device.cpp.i

Device.s: Device.cpp.s
.PHONY : Device.s

# target to generate assembly for a file
Device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Device.cpp.s
.PHONY : Device.cpp.s

GpuMemAlloc.o: GpuMemAlloc.cpp.o
.PHONY : GpuMemAlloc.o

# target to build an object file
GpuMemAlloc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/GpuMemAlloc.cpp.o
.PHONY : GpuMemAlloc.cpp.o

GpuMemAlloc.i: GpuMemAlloc.cpp.i
.PHONY : GpuMemAlloc.i

# target to preprocess a source file
GpuMemAlloc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/GpuMemAlloc.cpp.i
.PHONY : GpuMemAlloc.cpp.i

GpuMemAlloc.s: GpuMemAlloc.cpp.s
.PHONY : GpuMemAlloc.s

# target to generate assembly for a file
GpuMemAlloc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/GpuMemAlloc.cpp.s
.PHONY : GpuMemAlloc.cpp.s

Images.o: Images.cpp.o
.PHONY : Images.o

# target to build an object file
Images.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Images.cpp.o
.PHONY : Images.cpp.o

Images.i: Images.cpp.i
.PHONY : Images.i

# target to preprocess a source file
Images.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Images.cpp.i
.PHONY : Images.cpp.i

Images.s: Images.cpp.s
.PHONY : Images.s

# target to generate assembly for a file
Images.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Images.cpp.s
.PHONY : Images.cpp.s

MeshGen.o: MeshGen.cpp.o
.PHONY : MeshGen.o

# target to build an object file
MeshGen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/MeshGen.cpp.o
.PHONY : MeshGen.cpp.o

MeshGen.i: MeshGen.cpp.i
.PHONY : MeshGen.i

# target to preprocess a source file
MeshGen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/MeshGen.cpp.i
.PHONY : MeshGen.cpp.i

MeshGen.s: MeshGen.cpp.s
.PHONY : MeshGen.s

# target to generate assembly for a file
MeshGen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/MeshGen.cpp.s
.PHONY : MeshGen.cpp.s

Noise.o: Noise.cpp.o
.PHONY : Noise.o

# target to build an object file
Noise.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Noise.cpp.o
.PHONY : Noise.cpp.o

Noise.i: Noise.cpp.i
.PHONY : Noise.i

# target to preprocess a source file
Noise.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Noise.cpp.i
.PHONY : Noise.cpp.i

Noise.s: Noise.cpp.s
.PHONY : Noise.s

# target to generate assembly for a file
Noise.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Noise.cpp.s
.PHONY : Noise.cpp.s

PlanetRenderer.o: PlanetRenderer.cpp.o
.PHONY : PlanetRenderer.o

# target to build an object file
PlanetRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/PlanetRenderer.cpp.o
.PHONY : PlanetRenderer.cpp.o

PlanetRenderer.i: PlanetRenderer.cpp.i
.PHONY : PlanetRenderer.i

# target to preprocess a source file
PlanetRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/PlanetRenderer.cpp.i
.PHONY : PlanetRenderer.cpp.i

PlanetRenderer.s: PlanetRenderer.cpp.s
.PHONY : PlanetRenderer.s

# target to generate assembly for a file
PlanetRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/PlanetRenderer.cpp.s
.PHONY : PlanetRenderer.cpp.s

ResultCheck.o: ResultCheck.cpp.o
.PHONY : ResultCheck.o

# target to build an object file
ResultCheck.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/ResultCheck.cpp.o
.PHONY : ResultCheck.cpp.o

ResultCheck.i: ResultCheck.cpp.i
.PHONY : ResultCheck.i

# target to preprocess a source file
ResultCheck.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/ResultCheck.cpp.i
.PHONY : ResultCheck.cpp.i

ResultCheck.s: ResultCheck.cpp.s
.PHONY : ResultCheck.s

# target to generate assembly for a file
ResultCheck.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/ResultCheck.cpp.s
.PHONY : ResultCheck.cpp.s

Shader.o: Shader.cpp.o
.PHONY : Shader.o

# target to build an object file
Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Shader.cpp.o
.PHONY : Shader.cpp.o

Shader.i: Shader.cpp.i
.PHONY : Shader.i

# target to preprocess a source file
Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Shader.cpp.i
.PHONY : Shader.cpp.i

Shader.s: Shader.cpp.s
.PHONY : Shader.s

# target to generate assembly for a file
Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Shader.cpp.s
.PHONY : Shader.cpp.s

Swapchain.o: Swapchain.cpp.o
.PHONY : Swapchain.o

# target to build an object file
Swapchain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Swapchain.cpp.o
.PHONY : Swapchain.cpp.o

Swapchain.i: Swapchain.cpp.i
.PHONY : Swapchain.i

# target to preprocess a source file
Swapchain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Swapchain.cpp.i
.PHONY : Swapchain.cpp.i

Swapchain.s: Swapchain.cpp.s
.PHONY : Swapchain.s

# target to generate assembly for a file
Swapchain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Swapchain.cpp.s
.PHONY : Swapchain.cpp.s

Textures.o: Textures.cpp.o
.PHONY : Textures.o

# target to build an object file
Textures.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Textures.cpp.o
.PHONY : Textures.cpp.o

Textures.i: Textures.cpp.i
.PHONY : Textures.i

# target to preprocess a source file
Textures.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Textures.cpp.i
.PHONY : Textures.cpp.i

Textures.s: Textures.cpp.s
.PHONY : Textures.s

# target to generate assembly for a file
Textures.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/Textures.cpp.s
.PHONY : Textures.cpp.s

TriangleBisection.o: TriangleBisection.cpp.o
.PHONY : TriangleBisection.o

# target to build an object file
TriangleBisection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/TriangleBisection.cpp.o
.PHONY : TriangleBisection.cpp.o

TriangleBisection.i: TriangleBisection.cpp.i
.PHONY : TriangleBisection.i

# target to preprocess a source file
TriangleBisection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/TriangleBisection.cpp.i
.PHONY : TriangleBisection.cpp.i

TriangleBisection.s: TriangleBisection.cpp.s
.PHONY : TriangleBisection.s

# target to generate assembly for a file
TriangleBisection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/TriangleBisection.cpp.s
.PHONY : TriangleBisection.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testApp.dir/build.make CMakeFiles/testApp.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... testApp"
	@echo "... Buffers.o"
	@echo "... Buffers.i"
	@echo "... Buffers.s"
	@echo "... Camera.o"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... CbtBisection.o"
	@echo "... CbtBisection.i"
	@echo "... CbtBisection.s"
	@echo "... CbtGpuBisection.o"
	@echo "... CbtGpuBisection.i"
	@echo "... CbtGpuBisection.s"
	@echo "... Context.o"
	@echo "... Context.i"
	@echo "... Context.s"
	@echo "... Device.o"
	@echo "... Device.i"
	@echo "... Device.s"
	@echo "... GpuMemAlloc.o"
	@echo "... GpuMemAlloc.i"
	@echo "... GpuMemAlloc.s"
	@echo "... Images.o"
	@echo "... Images.i"
	@echo "... Images.s"
	@echo "... MeshGen.o"
	@echo "... MeshGen.i"
	@echo "... MeshGen.s"
	@echo "... Noise.o"
	@echo "... Noise.i"
	@echo "... Noise.s"
	@echo "... PlanetRenderer.o"
	@echo "... PlanetRenderer.i"
	@echo "... PlanetRenderer.s"
	@echo "... ResultCheck.o"
	@echo "... ResultCheck.i"
	@echo "... ResultCheck.s"
	@echo "... Shader.o"
	@echo "... Shader.i"
	@echo "... Shader.s"
	@echo "... Swapchain.o"
	@echo "... Swapchain.i"
	@echo "... Swapchain.s"
	@echo "... Textures.o"
	@echo "... Textures.i"
	@echo "... Textures.s"
	@echo "... TriangleBisection.o"
	@echo "... TriangleBisection.i"
	@echo "... TriangleBisection.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

